language: node_js

node_js:
  - node

services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker image build -t $PROJECT_NAME:$PROJECT_VERSION .
  - docker image tag $PROJECT_NAME:$PROJECT_VERSION $DOCKER_USERNAME/$PROJECT_NAME:$PROJECT_VERSION
  - docker image push $DOCKER_USERNAME/$PROJECT_NAME

branches:
  only:
    - master