apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: venues-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/rewrite-target: /graphql
spec:
  tls:
    - hosts:
        - rso-api.westeurope.cloudapp.azure.com
      secretName: tls-secret-prd
  rules:
    - host: rso-api.westeurope.cloudapp.azure.com
      http:
        paths:
          - path: /venues
            backend:
              serviceName: venues
              servicePort: 80
